plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.quotationcalculator'
    compileSdk 35

    defaultConfig {
        applicationId 'com.example.quotationcalculator'
        minSdk 23
        targetSdk 34
        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
